data: data/preprocessed_ubuntu_dataset/ubuntu_dataset_preprocessed
save_model: data/model/transformer/model.transformer_asm_name
save_checkpoint_steps: 27425
keep_checkpoint: 100
seed: 3435
train_steps: 1000000
valid_steps: 27425
warmup_steps: 8000
report_every: 100
tensorboard: True
tensorboard_log_dir: data/model/transformer/

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
focal_loss: True

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0
