data: data/preprocessed_ubuntu_dataset/ubuntu_dataset_preprocessed
save_model: data/model/seq2seq/model.seq2seq_asm_name
exp: seq2seq
save_checkpoint_steps: 10000
keep_checkpoint: 5
seed: 3435
train_steps: 1000000
valid_steps: 27425
warmup_steps: 8000
report_every: 100
tensorboard: True
tensorboard_log_dir: data/model/seq2seq/model.seq2seq_asm_name

decoder_type: rnn
encoder_type: brnn
word_vec_size: 128
enc_rnn_size: 256
dec_rnn_size: 256
enc_layers: 2
dec_layers: 2
global_attention: mlp
global_attention_function: softmax
bridge: True
generator_function: softmax

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: rsqrt
learning_rate: 2.0
max_grad_norm: 1.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks: 0

